import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { ThemeProvider } from "../components/theme-provider";
import { ModeToggle } from "./mode-toggle";
import NavBar from "./(browser)/_component/navbar/NavBar";
import Sidebar from "./(browser)/_component/sidebar/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider appearance={{ baseTheme: dark }}>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            storageKey="gamehub"
          >
            {/* <ModeToggle /> */}
            <NavBar />
            <div className="flex h-full pt-20">
              <Sidebar />
              <div className="ml-60">{children}</div>
            </div>
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
